# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

time_zone: Australia/Brisbane

# values of custom fields (defined in src/settings.yml)
custom_fields: { "period": "year" }

# override variables
variables:
  trmnl: {}
  testing_date_time: "2026-02-25T23:00:00"
