---
strategy: static
no_screen_padding: 'no'
dark_mode: 'no'
static_data: 
polling_verb: get
polling_url: ''
polling_headers: ''
polling_body: ''
id: 249658
custom_fields:
- keyname: period
  field_type: select
  options:
  - Day
  - Week
  - Month
  - Year
  default: day
  name: Period of Time
  description: Current period of time to use for hourglass
name: Hourglass
refresh_interval: 30
